<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View_mx_Checkbox_background</name>
   <tag></tag>
   <elementGuidId>52db80bd-9488-4047-b15a-416ae4b75153</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mx_Checkbox_background</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/section/div[1]/div[2]/div[3]/main/div/div/ul/li/div/div[3]/span/label/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx_Checkbox_background</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;matrixchat&quot;)/div[@class=&quot;mx_MatrixChat_wrapper&quot;]/div[@class=&quot;mx_MatrixChat&quot;]/div[@class=&quot;mx_RoomView_wrapper&quot;]/main[@class=&quot;mx_SpaceRoomView&quot;]/div[@class=&quot;mx_MainSplit&quot;]/div[@class=&quot;mx_SpaceRoomView_landing&quot;]/ul[@class=&quot;mx_SpaceHierarchy_list&quot;]/li[@class=&quot;mx_SpaceHierarchy_roomTileWrapper&quot;]/div[@class=&quot;mx_AccessibleButton mx_SpaceHierarchy_roomTile&quot;]/div[@class=&quot;mx_SpaceHierarchy_actions&quot;]/span[@class=&quot;mx_Checkbox mx_Checkbox_hasKind mx_Checkbox_kind_solid&quot;]/label[1]/div[@class=&quot;mx_Checkbox_background&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='matrixchat']/div/div[2]/div[3]/main/div/div/ul/li/div/div[3]/span/label/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Joined'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
   </webElementXpaths>
</WebElementEntity>
